groupplace_index:
    path:     /
    defaults: { _controller: "GestionBundle:GroupPlace:index" }
    methods:  GET

groupplace_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:GroupPlace:show" }
    methods:  GET

groupplace_new:
    path:     /new
    defaults: { _controller: "GestionBundle:GroupPlace:new" }
    methods:  [GET, POST]

groupplace_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:GroupPlace:edit" }
    methods:  [GET, POST]

groupplace_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:GroupPlace:delete" }
    methods:  DELETE
