kindwork_index:
    path:     /
    defaults: { _controller: "GestionBundle:KindWork:index" }
    methods:  GET

kindwork_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:KindWork:show" }
    methods:  GET

kindwork_new:
    path:     /new
    defaults: { _controller: "GestionBundle:KindWork:new" }
    methods:  [GET, POST]

kindwork_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:KindWork:edit" }
    methods:  [GET, POST]

kindwork_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:KindWork:delete" }
    methods:  DELETE
