place_index:
    path:     /
    defaults: { _controller: "GestionBundle:Place:index" }
    methods:  GET

place_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Place:show" }
    methods:  GET

place_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Place:new" }
    methods:  [GET, POST]

place_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Place:edit" }
    methods:  [GET, POST]

place_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Place:delete" }
    methods:  DELETE
