typeintervention_index:
    path:     /
    defaults: { _controller: "GestionBundle:TypeIntervention:index" }
    methods:  GET

typeintervention_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:TypeIntervention:show" }
    methods:  GET

typeintervention_new:
    path:     /new
    defaults: { _controller: "GestionBundle:TypeIntervention:new" }
    methods:  [GET, POST]

typeintervention_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:TypeIntervention:edit" }
    methods:  [GET, POST]

typeintervention_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:TypeIntervention:delete" }
    methods:  DELETE
