<?php

namespace GestionBundle\Repository;

/**
 * GroupPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
