<?php

namespace GestionBundle\Repository;

/**
 * LaborCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaborCostRepository extends \Doctrine\ORM\EntityRepository
{       
}
