<?php

namespace GestionBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAlphabeticOrder()
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.titlePlace', 'ASC')
            ->where('p.infoActivePlace = true');
        return $qb;
    }
}
