<?php

namespace GestionBundle\Repository;

/**
 * TypeInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeInterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAlphabeticOrder()
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.titleTypeIntervention', 'ASC')
            ->where('t.infoActiveTypeIntervention = true');
        return $qb;
    }
}
